### ISSUE TITLE
what is COOL_STORE in APP_FOLDER = 'COOL_STORE';

### ISSUE THREAD

**Issue by Sreenivas7463** [mithilesh-parmar/Flutter-store#1]
what is COOL_STORE in APP_FOLDER = 'COOL_STORE';

**Comment by mithilesh-parmar** [comment]
It is used for local storage to save favourite and cart added products to local storage for caching.
you can check out the code in class cart_state.dart on line 108 I have used a function to save objects to local storage.

**Comment by Sreenivas7463** [comment]
Hi Mithilesh-Parmar/Flutter-Store,

                                                     I am using Wordpress
with woocommerce. I generated Keys and placed in coding. and replace with
my web url. But it is not showing in generated app. Is there any
Woocommerce api have to install in my project If yes please specify
location.

**Comment by mithilesh-parmar** [comment]
Where did you place your api keys?

**Comment by Sreenivas7463** [comment]
Flutter-store <https://github.com/mithilesh-parmar/Flutter-store>/lib
<https://github.com/mithilesh-parmar/Flutter-store/tree/master/lib>/utils
<https://github.com/mithilesh-parmar/Flutter-store/tree/master/lib/utils>/
constants.dart

in constants.dart file i placed my keys

**Comment by mithilesh-parmar** [comment]
Did you change URL_CLOUD?
This will be the URL of the website or the server where you have hosted your website.

**Comment by Sreenivas7463** [comment]
Yes i changed URL_CLOUD to my site address

**Comment by mithilesh-parmar** [comment]
could you mention your website link..

**Comment by Sreenivas7463** [comment]
https://adyourworld.com/ecommwp/

**Comment by mithilesh-parmar** [comment]
Should Work Maybe Your theme could be causing issues..

**Comment by mithilesh-parmar** [comment]
Also what error does it show in logs?
