### ISSUE TITLE
hello any update for the project

### ISSUE THREAD

**Issue by Layalekiameh** [mithilesh-parmar/Flutter-store#4]
Not working at all a lots of problem
[+81646 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.5.9/lib/src/gesture/extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'.
[   +2 ms]         animation: animation,
[        ]         ^^^^^^^^^
[        ] ../../flutter/packages/flutter/lib/src/cupertino/route.dart:546:3: Context: Found this candidate, but the arguments don't match.
[        ]   CupertinoFullscreenDialogTransition({
[        ]   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] ../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
[        ]   PictureStream();
[        ]   ^^^^^^^^^^^^^
[+1086 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
[        ] abstract class PictureStreamCompleter extends Diagnosticable {
[        ]                ^
[+5399 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/imac/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/imac/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2m 38s
[{"event":"app.progress","params":{"appId":"c14bb3fb-0921-45c1-b4e2-d03da1cd2ff0","id":"0","progressId":null,"finished":true}}]
[+3436 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:474:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by mithilesh-parmar** [comment]
Hi,

This project is outdated, it is not to be used as is but to serve as a guide for the architecture, custom widgets, and most importantly API usage. 

You need to specify your own woo-commerce backend server to for app to work as expected. There are packages which are not compatible with new Dart SDK and flutter versions. 

I'm planning to update the project with latest packages and few more improvements but currently I'm busy with client work. 
Hit me up if you have any problem.  

Thankyou
